services:
#  scraper:
#    command: python main.py
#    build:
#      context: scraper
#    volumes:
#        - ./downloads:/app/downloads
#    environment:
#      SEARCH: ${SEARCH}
#      LUMMMI_SCRAPER: ${LUMMMI_SCRAPER}
#      PINTEREST_SCRAPER: ${PINTEREST_SCRAPER}
#      UNSPLASH_SCRAPER: ${UNSPLASH_SCRAPER}
#      PEXELS_SCRAPER: ${PEXELS_SCRAPER}
#      PIXABAY_SCRAPER: ${PIXABAY_SCRAPER}
#      STOCKSNAP_SCRAPER: ${STOCKSNAP_SCRAPER}
#      SCROLL_TIMEOUT: ${SCROLL_TIMEOUT}

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    restart: unless-stopped

  fiftyone:
    build:
      context: pyrust
      dockerfile: Dockerfile.viewer
    container_name: fiftyone
    ports:
      - "5151:5151"
    volumes:
      - ./pyrust/src/data:/app/data

  front:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "8501:8501"
    volumes:
      - ./front/src:/app/src
      - ./pyrust/src/data:/app/data
    environment:
      API_URL: ${API_URL}

volumes:
  mongo-data:
