services:
#  scraper:
#    command: python main.py
#    build:
#      context: scraper
#    volumes:
#        - ./downloads:/app/downloads
#    environment:
#      SEARCH: ${SEARCH}
#      LUMMMI_SCRAPER: ${LUMMMI_SCRAPER}
#      PINTEREST_SCRAPER: ${PINTEREST_SCRAPER}
#      UNSPLASH_SCRAPER: ${UNSPLASH_SCRAPER}
#      PEXELS_SCRAPER: ${PEXELS_SCRAPER}
#      PIXABAY_SCRAPER: ${PIXABAY_SCRAPER}
#      STOCKSNAP_SCRAPER: ${STOCKSNAP_SCRAPER}
#      SCROLL_TIMEOUT: ${SCROLL_TIMEOUT}

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    restart: unless-stopped


#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongodb
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: admin
#    restart: unless-stopped
#    depends_on:
#      - mongodb

  fiftyone:
    build: pyrust
    container_name: fiftyone-viewer
    ports:
      - "5151:5151"
    volumes:
      - ./pyrust/src/data:/app/data

volumes:
  mongo-data:
