services:
  scraper:
    command: python main.py
    build:
      context: scraper
    volumes:
        - ./downloads:/app/downloads
    environment:
      - SEARCH=natural landscape
      - LUMMMI_SCRAPER=false
      - PINTEREST_SCRAPER=true
      - UNSPLASH_SCRAPER=true
      - PEXELS_SCRAPER=true
      - SCROLL_TIMEOUT=600
